import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from "next/image";
import jordanai from "../public/jordan-rose-ai.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);


  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Jordan Rose Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons dark:text-white">Developed By: Jordan Rose</h1>
              <ul className="flex items-center">
                <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl dark:text-white" /></li>
                <li>
                  <a className="bg-gradient-to-r from-blue-500 to-blue-300 text-white px-4 py-2 rounded-md ml-8" href="https://www.linkedin.com/in/jordan-rose-589a3166/" target="_blank">Resume</a>
                </li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-blue-400 font-medium md:text-6xl">Jordan Rose</h2>
              <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Developer, Product Manager</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
                As a highly motivated and detail-oriented individual, I have a proven track record of success in both my business and technical pursuits. I pride myself on solid communication and problem-solving skills, and I enjoy continuously improving.
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-32 py-3 text-gray-600 dark:text-white">
                <a href="https://www.linkedin.com/in/jordan-rose-589a3166/" target="_blank">
                  <AiFillLinkedin />
                </a>
                <a href="https://github.com/jrose8775" target="_blank">
                  <AiFillGithub />
                </a>
            </div>
            <div className="relative mx-auto w-80 h-80 mt-20 mb-20 overflow-hidden md:h-96 md:w-96">
              <Image className="rounded-full" src={jordanai} />
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white">Experience</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I have experience as a software developer, with a strong background in programming languages such as <span className="text-blue-400">JavaScript</span> and <span className="text-blue-400">React</span> and experience developing and maintaining software applications for various industries.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                I have experience in software quality assurance, including developing and executing test plans, writing and maintaining test cases, and identifying and documenting defects in software applications.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                I have experience as a software product manager, responsible for leading cross-functional teams to define, prioritize, and deliver successful software products, using agile methodologies and data-driven decision making.
              </p>
            </div>
            <div className="lg:flex gap-10 justify-center dark:text-white">
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image className="mx-auto" src={design} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">Software Development</h3>
                <p className="py-2">Full Stack</p>
                <h4 className="py-4 text-blue-400">Programming Languages &amp; Tools</h4>
                <p className="text-gray-800 py-1 dark:text-white">JavaScript &amp; TypeScript</p>
                <p className="text-gray-800 py-1 dark:text-white">React</p>
                <p className="text-gray-800 py-1 dark:text-white">NodeJS</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image className="mx-auto" src={code} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">Quality Assurance</h3>
                <p className="py-2">Eye for detail</p>
                <h4 className="py-4 text-blue-400">How I Accomplish</h4>
                <p className="text-gray-800 py-1 dark:text-white">Manual Application Validation</p>
                <p className="text-gray-800 py-1 dark:text-white">User &amp; Business Needs</p>
                <p className="text-gray-800 py-1 dark:text-white">Testing Edge Cases</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image className="mx-auto" src={consulting} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">Product Management</h3>
                <p className="py-2">Efficient Teams</p>
                <h4 className="py-4 text-blue-400">Approach</h4>
                <p className="text-gray-800 py-1 dark:text-white">Unblocking Developers</p>
                <p className="text-gray-800 py-1 dark:text-white">Writing User Stories</p>
                <p className="text-gray-800 py-1 dark:text-white">Documentation</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                Below is a short-list of the main projects I have created and worked on personally.
              </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image className="rounded-lg object-cover w-full h-full" width={500} height={500} src={web1} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image className="rounded-lg object-cover w-full h-full" width={500} height={500} src={web2} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image className="rounded-lg object-cover w-full h-full" width={500} height={500} src={web3} />
              </div>
              <div className="basis-1/3 flex-1">
                <Image className="rounded-lg object-cover w-full h-full" width={500} height={500} src={web4} />
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  )
}
